### ISSUE TITLE
CTRL+C 沒辦法終止程式

### ISSUE THREAD

**Issue by honeymagico** [SDpower/shioajicaller#1]
感謝你的程式很有幫助, 
但發現啟動WEBSOCKET服務後, 在終端介面按CTRL+C,
不會觸發KeyboardInterrupt, 沒辦法正常終止程式
不知道該如何解決?

**Comment by SDpower** [comment]
我都用docker 在執行，抱歉我會再找看看哪裡出問題。

**Comment by SDpower** [comment]
Close by #2
