### ISSUE TITLE
使用命令列帶參數 -api -secret 登入時, 會出錯

### ISSUE THREAD

**Issue by honeymagico** [SDpower/shioajicaller#5]
使用命令列帶參數 -api -secret 登入時, 會出錯如下

  File "C:\Projects\shioajicaller\shioajicaller\caller.py", line 172, in Login
    self._accounts = self._api.login(self._apiKey, self._secretKey,contracts_cb = self.ContractsDone())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\shioajicaller\.venv\Lib\site-packages\shioaji\shioaji.py", line 317, in login
    accounts, contract_download, person_id = self._solace.token_login(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 'key' has incorrect type (expected str, got list)

查是這裡使用了NARGS, 所以API及SECRET都變成list型別:

https://github.com/SDpower/shioajicaller/blob/0df71e1d7e9b2a69a3e9a10db00fc54d7933b886/shioajicaller/cli/__init__.py#L53

請問有什麼特殊用意嗎?

**Comment by SDpower** [comment]
I will fix it.
